### missing data
POST http://localhost:3001/api/persons

### missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jon Doe"
}

### missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "666-666"
}

### invalid number format
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Invalid phone",
  "number": "6-666-666"
}


### valid
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jon Doe",
  "number": "666-66666666"
}